import{db,doc,collection,onSnapshot}from'./firebase.js';import{escapeHtml,formatType,clamp}from'./utils.js';import{bindNetworkStatus}from'./ui.js';const screen=document.getElementById('screen'),sessionRef=doc(db,'session','current');let session={state:'idle'},question=null,responses=[],uq,ur;bindNetworkStatus();onSnapshot(sessionRef,s=>{session=s.exists()?s.data():{state:'idle'};load()});
function load(){uq?.();ur?.();question=null;responses=[];if(!session.activeQuestionId)return idle();loading();uq=onSnapshot(doc(db,'questions',session.activeQuestionId),s=>{if(!s.exists())return idle();question={id:s.id,...s.data()};render()});ur=onSnapshot(collection(db,'questions',session.activeQuestionId,'responses'),s=>{responses=s.docs.map(d=>d.data());render()})}function audienceUrl(){return location.href.replace(/display\.html.*$/,'index.html')}
function idle(){screen.innerHTML=`<section class="display-idle"><div class="display-brand"><span class="brand-mark">E×M</span> ESG × MM</div><h1>每個聲音，都值得被看見。</h1><div class="join-layout"><div id="joinQr" class="join-qr"></div><div><span class="eyebrow">SCAN TO JOIN</span><h2>掃描 QR Code<br>加入即時互動</h2><p class="muted">${escapeHtml(audienceUrl())}</p></div></div></section>`;if(window.QRCode){const box=document.getElementById('joinQr');box.innerHTML='';new QRCode(box,{text:audienceUrl(),width:220,height:220,colorDark:'#073B5C',colorLight:'#ffffff'})}}function loading(){screen.innerHTML='<div class="display-loading"><span class="spinner"></span><p>正在載入題目</p></div>'}
function shell(content){const part=String(question.part||formatType(question.type)).replaceAll('全員互動','ESG × MM');screen.innerHTML=`<header class="display-top"><div class="display-brand"><span class="brand-mark">E×M</span> ESG × MM</div><div class="voting-progress"><div class="progress"><i style="width:${Math.min(100,responses.length*3)}%"></i></div><b>${responses.length} 票</b></div></header><section class="display-main"><span class="eyebrow">${escapeHtml(part)}</span><h1 class="display-title">${escapeHtml(question.title)}</h1><div class="display-results">${content}</div></section>`}
function render(){if(!question)return;if(session.state==='lottery')return lottery();if(session.state==='live')return shell(`<div class="display-idle"><div class="orb">◉</div><h2>投票進行中</h2><p class="muted">答案正即時湧入，結果將由主持人公布。</p><div class="big-number">${responses.length}</div></div>`);if(session.state==='locked')return shell('<div class="display-idle"><h2>投票已截止</h2><p class="muted">準備公布結果…</p></div>');if(session.state!=='closed')return shell('<div class="display-idle"><h2>準備開始</h2></div>');results()}
function results(){const t=question.type;if(['wordcloud','open'].includes(t))return words();if(['slider','rating'].includes(t))return average();return bars()}
function bars(){let opts=question.options||[];if(question.type==='emoji')opts=['😍','😊','😐','🤔','😢'];if(question.type==='rating')opts=['1','2','3','4','5'];if(question.type==='yesno'&&opts.length<2)opts=['是','否'];const counts=opts.map(()=>0);responses.forEach(r=>{const vals=Array.isArray(r.value)?r.value:[r.value];vals.forEach(v=>{if(Number.isInteger(v)&&counts[v]!=null)counts[v]++})});if(question.type==='ranking'){counts.fill(0);responses.forEach(r=>Array.isArray(r.value)&&r.value.forEach((v,i)=>{if(counts[v]!=null)counts[v]+=opts.length-i}))}const max=Math.max(1,...counts);shell(opts.map((o,i)=>`<div class="bar-row ${question.type==='quiz'&&i===question.correctIndex?'correct':''}"><span>${escapeHtml(o)}</span><div class="bar-track"><div class="bar-fill" style="width:${counts[i]/max*100}%"></div></div><b>${counts[i]}</b></div>`).join(''))}
function average(){const nums=responses.map(r=>Number(r.value)).filter(Number.isFinite),avg=nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0;shell(`<div class="display-idle"><span class="eyebrow">AVERAGE SCORE</span><div class="big-number">${avg.toFixed(1)}</div><p class="muted">共 ${nums.length} 份有效回答</p></div>`)}
function words(){const values=responses.flatMap(r=>Array.isArray(r.value)?r.value:[r.value]).map(String).filter(Boolean),counts=new Map;values.forEach(v=>counts.set(v,(counts.get(v)||0)+1));const words=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,36);if(!words.length)return shell('<div class="display-idle"><h2>等待第一個答案</h2></div>');shell(`<div class="word-cloud">${words.map(([w,n],i)=>`<span class="word" style="font-size:${clamp(24+n*9,24,78)}px;left:${(i*37)%86}%;top:${(i*29)%82}%;animation-delay:${i*.03}s">${escapeHtml(w)}</span>`).join('')}</div>`)}
function lottery(){const pool=responses.filter(r=>r.nickname);if(!pool.length)return shell('<div class="display-idle"><h2>還沒有可抽選的參與者</h2></div>');const winner=pool[Math.floor(Math.random()*pool.length)];shell(`<div class="display-idle"><span class="eyebrow">LUCKY DRAW</span><p class="muted">恭喜本次幸運得主</p><div class="big-number">${escapeHtml(winner.nickname)}</div></div>`)}
